### ISSUE TITLE
unable to find price for flipkart items

### ISSUE THREAD

**Issue by maxmill** [dylants/price-finder#106]
This issue is coming back for a new reason. The description meta tag no longer contains the pricing info.  Could you try rebuilding master on TravisCI?

https://github.com/dylants/price-finder/issues/98

hope this helps - I am able to retrieve the price (from browser console) using 
$('#sellerName + li > a > span + span + span').innerHTML
.split('-->')[3]
.split('<!--')[0]

**Comment by dylants** [comment]
Yeah, this looks like it's more of what was described originally in #98.  Only this time they may have fixed all the available loop holes that exist.  At this point it's just not very feasible to grab the price from the page without first loading a whole bunch of javascript complete with session details (they somehow log you in, even just private browsing).  They also seem to have an API, but again, this requires session (authentication).

Is this really something we should support going forward.  I'd like to just remove the functionality at this point...
