### ISSUE TITLE
wrong price amazon, using the 3-year protection price

### ISSUE THREAD

**Issue by teebu** [dylants/price-finder#113]
Im doing some testing, this says this: https://www.amazon.com/dp/B016XTADG2
```
{ price: 3.73,
  category: 'Other',
  name: 'Anker SoundCore Bluetooth Speaker with 24-Hour Playtime, 66-Foot Bluetooth Range & Built-in Mic, Dual-Driver Portable Wireless Speaker with Low Harmonic Distortion and Superior Sound - Black' }
```

Amazon Product API:
```
  offerPrice: '$79.99',
  lowestPrice: '$26.99',
```

**Comment by teebu** [comment]
https://www.amazon.com/gp/product/B00NCSIN4W

Looks like its reading the price of the `Include 3-Year Protection for $7.47`

**Comment by dylants** [comment]
Hopefully fixed this issue in #114, please let me know if it does not work after that change. Thanks!

**Comment by teebu** [comment]
when will the update reach npm?

**Comment by dylants** [comment]
Sorry, I didn't know if this was something you wanted to check prior to a release. I'll put together a bugfix release and have it out soon!

**Comment by dylants** [comment]
@teebu [4.3.1](https://github.com/dylants/price-finder/releases/tag/4.3.1) has been published to npm

**Comment by teebu** [comment]
Thanks, seems to work good in those cases, as far as i can tell.
