### ISSUE TITLE
User agent support

### ISSUE THREAD

**Issue by duoli** [dylants/price-finder#117]
It would be very useful to have user-agent support to avoid being blacklisted by shopping sites.

**Comment by dylants** [comment]
Certainly! It's funny, we had this feature originally but took it out after the `request` -> `superagent` change made in #64. But this can be added back in if needed.

Strange though, do you know that shopping sites will blacklist without certain headers? I've not found that to matter much for me. The only thing that really seems to cause issues is the rate of requests. I add large sleeps between each request to avoid these problems. But you have found that the user agent header alleviates these issues?

As far as how this can be done, adding the header(s) to the request should work as you've suggested, looking at the documentation of `superagent` here: https://github.com/visionmedia/superagent

The trick in this maybe how we accept the headers as input? We could make it a 1-1 as you've suggested (user agent, etc), or allow them to specify any header key/value.

**Comment by dylants** [comment]
Is this request still needed? If not I will close the issue.

**Comment by dylants** [comment]
Closing the issue since it appears it is no longer needed. Please let me know if this is not the case.
