### ISSUE TITLE
Async loading

### ISSUE THREAD

**Issue by Shuunen** [dylants/price-finder#2]
Hey,

First, thanks for your work, it work well with the supported sites,

I'm having an issue when I try to get a price that is not in the DOM when page give a 200 status code, it might be loaded and injected after page loaded.

Do you have an idea on how to handle this ?

ps: I forked this example on my repo

**Comment by dylants** [comment]
Hey @Shuunen, glad you're able to use this, happy to help!

Some sites are loading the price and/or page details after the initial page load, sometimes through alternate requests.  What I try to do is find the request that loads the price, and see how they generated that URL to request the price information.  It looks like a similar situation in the case of your example.

I was able to put together a working test to load the price from your example in your repo, please check it out:

```javascript
var request = require("request");
var cheerio = require("cheerio");

// original url ==> http://www.priceminister.com/mfp/2003443/rayman-legends-jeu-video#pid=206756671
var url = "http://www.priceminister.com/mfp?cid=2003443&urlname=rayman-legends-jeu-video&pid=206756671&action=advlstmeta";

request(url, function(err, response, body) {
    $ = cheerio.load(body);

    var priceContainer = $('#advert_list .priceInfos').first();
    var price = priceContainer.find('.price').text().trim();
    var shipping = priceContainer.find('.shipping .value').text().trim();

    price = parseFloat(price.replace(',', '.'));
    shipping = parseFloat(shipping.replace(',', '.'));

    price += shipping;

    console.log(price);
});
```

It looks like the details can be found in an alternate request, which takes the parameters from the first and puts them in the second.  If this works for you, I would recommend generating this alternate URL from the original one, and returning it in the `getURIForPageData` function.

**Comment by Shuunen** [comment]
You rock :) thanks i'm on it

**Comment by Shuunen** [comment]
getURIForPageData + regex => for the win, all works now :)
