### ISSUE TITLE
Node v4 support: Drop support for Node v0.x, iojs

### ISSUE THREAD

**Issue by dylants** [dylants/price-finder#28]
The current code base supports both the current version of Node (v4) and legacy versions (0.10, 0.12, iojs).  In order to continue to move forward with the technology, we're going to have to drop support for the legacy versions.  I suggest doing this within a major version bump.

**Comment by Shuunen** [comment]
ok, is there something to do ?

**Comment by dylants** [comment]
As I see it, there's a handful of things to do:
- Remove the legacy versions from the Travis CI file
- Use the [`engines`](https://docs.npmjs.com/files/package.json#engines) flag to specify support for only 4 and above
- Add a message in the readme to indicate this support restriction
- Switch from jshint to [eslint](http://eslint.org/)

Maybe more...?

**Comment by Shuunen** [comment]
i'm installing node 4 new package from nodejs.org

**Comment by dylants** [comment]
If you have the option, I'd recommend using [nvm](https://github.com/creationix/nvm).  It allows you to easily switch between versions of Node (and installs Node to your home directory, avoiding potential `sudo` invocations).

**Comment by Shuunen** [comment]
I'm on Windows :)
