### ISSUE TITLE
Add support for yen price

### ISSUE THREAD

**Issue by devil-tamachan** [dylants/price-finder#30]
```
site-utils.js@line 54

var EURO_SYMBOL_PREFIX = "€";
+ var YEN_PREFIX = "￥";

exports.processPrice = function(priceString) {

....

    } else if (_.includes(priceString, EURO_TEXT_PREFIX) ||
        _.includes(priceString, EURO_SYMBOL_PREFIX)) {
        logger.log("found euro in price, converting to number...");
        price = accounting.unformat(priceString, ",");
+    } else if (_.includes(priceString, YEN_PREFIX)) {
+        logger.log("found yen in price, converting to number...");
+        price = accounting.unformat(priceString);
    } else {
        // unknown price type!!
        logger.error("unknown price type, unable to process, returning -1");
        price = -1;
    }
```

**Comment by dylants** [comment]
I'd be happy to add this, but since it looks like you already wrote the code, would you want to submit a pull request for the feature?  If not, that's fine, just wanted to give you the opportunity :)

Either way, do you mind listing the ways in which a Yen price may appear?  We'll make sure these are part of the unit tests to validate the feature fulfills the request.

**Comment by devil-tamachan** [comment]
Hi dylants,

YEN_TEXT_PREFIX sample (need sites/surugaya.js - http://pastebin.com/EqWt3mK9): http://www.suruga-ya.jp/product/detail/104000921000
YEN_SYMBOL_PREFIX sample: http://www.amazon.co.jp/o/ASIN/B00Y3TMKKM/

Cheers!

---
tamachan

**Comment by dylants** [comment]
Thanks for the examples, @devil-tamachan, very much appreciated!  I've commented on the pull request you've opened.  Once the pull request is merged, if you'd like, feel free to add the work you've done in `SurugayaSite` that's linked above -- good stuff :smile:

**Comment by dylants** [comment]
This has been completed via #32
