### ISSUE TITLE
Newegg end to end test fails

### ISSUE THREAD

**Issue by dylants** [dylants/price-finder#49]
Running the newegg e2e test fails because it can't find the price of the item.  What's weird is that the selector, `#singleFinalPrice`, looks like it should work, but it doesn't.

**Comment by dylants** [comment]
I believe using `'.price-current'` as the selector works...

**Comment by dylants** [comment]
I'm now somewhat convinced that the price is not returned in the original HTML request, but somehow later injected on the page.

**Comment by dylants** [comment]
@rajkumarpb Have you seen this problem?  Or did you see it when you were originally implementing the Newegg site?  Please take a look at #50 to see what you think.

**Comment by rajkumarpb** [comment]
@dylants It was working fine. I did run e2e tests and it was working just fine. When I tested, I find that the price is available in a div #singleFinalPrice. Let me check it once again and fix it.

**Comment by dylants** [comment]
@rajkumarpb Unfortunately because the end to end test cases can run into issues with captcha's and other things, Travis does not run them.  Though this problem certainly highlights the need to run them.  Perhaps we should look at including some set of end to end testcases in Travis, or reduce the size of the end to end testcases... I'm not sure.

At this time Travis only runs the unit tests, not the end to end.  So it's validating the functionality of each file, but not the combined ability to find prices.

**Comment by dylants** [comment]
I created #52 to address this issue going forward, will go ahead and fix the Newegg issue found here.
