### ISSUE TITLE
Include e2e tests in Travis CI build

### ISSUE THREAD

**Issue by dylants** [dylants/price-finder#52]
Currently the Travis CI builds only run the linter and unit tests, not the end to end tests.  This can lead to unknown problems when the end to end integration does not function but the build shows green (as found with #49).

We need to either include all or at least some of the end to end tests in the Travis CI build to get some warning of possible problems.  The original reason these were kept out was because of fear of captcha's or other blocks when causing these external services to hit real URLs in the test.  Also, some of these tests require API keys (Best Buy) which is assigned to a user and would not be secure to post in the public CI build.  So all of these considerations would need to be included.

And who knows, maybe after all this we leave the end to end tests out of the Travis CI build and continue to do this manually.  It just needs to be addressed.

**Comment by dylants** [comment]
If we _were_ to do this, one suggestion would be to do the following:
- Create a new grunt task `ci` and include that in the package.json as `npm run ci`
- Have the grunt task specify the `CI` environment variable true via the [grunt-env](https://www.npmjs.com/package/grunt-env) package
- Create a new goal for the `jasmine_nodejs` grunt plugin to run ci tests, which include both the unit and end to end tests
- In each site's end to end test, check to see if the `CI` environment variable is set, and if so, run a test on only 1 site.  This verifies something but doesn't check everything to avoid spamming the site in CI.
- I believe the tests would need to use the `jasmine.DEFAULT_TIMEOUT_INTERVAL` to set the timeout when running through grunt.

But the real question is should we?  I'm not sure what implications this has on Travis since these tests are somewhat brittle and make web requests.  Is this a CI test?

**Comment by rajkumarpb** [comment]
I never knew that Travis wouldn't run e2e! That is not a CI test, and I think we need to find another way!!!

**Comment by rajkumarpb** [comment]
How about using Nightwatch.js instead? It seems to integrate well with CI and it is lot more easier.

**Comment by dylants** [comment]
Nightwatch is interesting, and I had not heard of that until now.  It looks more like a framework where you would author your end to end tests, rather than a platform which can run _any_ kind of tests.  I'm not sure it can run our existing tests in their current form.

Looking in parallel at what Travis CI offers, they mention how to handle something like this pretty specifically here: https://docs.travis-ci.com/user/speeding-up-the-build/#Parallelizing-your-builds-across-virtual-machines

I'm wondering if we should just add a long timeout in jasmine, longer retry wait times in price-finder for each test, and then include these end to end tests in the Travis CI build...

**Comment by dylants** [comment]
I went ahead and took a stab at adding the end to end tests to the Travis CI build, using the build matrix documentation referenced above.  I greatly increased both the retry sleep time (to avoid spamming the sites) and the individual end to end test timeout (since they can take a long time to finish).  It seems to work okay, amazingly enough, and can be found in this pull request: #55

**Comment by rajkumarpb** [comment]
Now Travis CI is taking a bit longer than it was before. But that's okay as long as the code will not break at later stage! Good work Dylan!
