### ISSUE TITLE
Testing Sites based on Affiliate IDs

### ISSUE THREAD

**Issue by rajkumarpb** [dylants/price-finder#57]
I'm working on adding few of the shopping site from India, like Flipkart and Snapdeal. To test them, we need to have an affiliateId, which is linked to my account. In that case, how can I push my test cases and make them pass without giving affiliate id? Because obviously TravisCI test's will fail. Please help me find workaround for this kinda scenario!

**Comment by dylants** [comment]
Hmm.. this is interesting.  These sites require an ID to use them?

I was able to add an encrypted value to the `.travis.yml` file, but had to encrypt it on my end.  I'm not sure what would happen if you encrypted the values, I'm guessing Travis decrypts using the repository user's credentials?  More information can be found here: https://docs.travis-ci.com/user/environment-variables/#Encrypted-Variables

**Comment by rajkumarpb** [comment]
@dylants Let me check that! BTW best buy also have the same kinda flow but it has some dummy value as key. But still e2e tests are passed with that key, how is that working? Can you explain this to me?

**Comment by dylants** [comment]
Travis allows us to encrypt values, I believe based on the hosted repos keys used to login to Travis CI.  So we have some encrypted data that represents those needed keys.  The link I pasted above should cover how this is possible.

**Comment by rajkumarpb** [comment]
I guess this issue is related to #59 ! If I can able to scrape without headers, that will be good. Until that let this issue sit idle.
