### ISSUE TITLE
Investigate alternate options to gather page data

### ISSUE THREAD

**Issue by dylants** [dylants/price-finder#63]
We're having problems using request to fetch the entire page data for a site.  For example, on some pages it seems to only return partial data rather than the full page contents.  Perhaps this is because of JavaScript run on the client (browser) after the initial page load, but for whatever reason it prohibits loading of the full page.

A couple example links:
http://www.newegg.com/Product/Product.aspx?Item=N82E16875705040
http://www.flipkart.com/nexus-6/p/itme7zd6w6qwgjuy?pid=MOBEFHHGZFKAZKY3

Both of these do not return the price displayed on the page.  It's unknown if they both have the same issue, or different.

**Comment by dylants** [comment]
One possibility is: https://github.com/lapwinglabs/x-ray-crawler

**Comment by dylants** [comment]
Or just what it uses by default: https://github.com/visionmedia/superagent

**Comment by rajkumarpb** [comment]
Time to explore, I guess. Let me see if these can do the magic.

**Comment by dylants** [comment]
After some investigation, using `superagent` greatly increased the performance of price-finder while also providing more detail in page data responses.  Because of this, a pull request was issued (#64) to switch from `request` to `superagent`.

Newegg does not supply the price data on the initial page response.  This can be verified by viewing the page source of a Newegg product page.  They must load it after the initial render, perhaps to keep others from easily finding the price.  So no HTTP GET will return the price data, we'll have to continue to use our current solution (regex'ing the page).

Flipkart _does_ return the price data in the initial page response, and by switching from `request` to `superagent` we were able to get this data easily:
```
$('*[itemprop="price"]').attr('content')
```
This same query was used on other pre-existing sites which reduces the complexity of the page query and improves the reliability of it for the future.  (If we don't have to query based on CSS classes and instead can use `itemprop` metadata, there should be less changes needed.)

In addition to all this, the page responses were faster and did not have the 503 error codes that would appear in certain situations when using `request`.

All of this points to reasons to switch to `superagent`.

**Comment by dylants** [comment]
Closing this with the inclusion of `superagent` into price-finder via #64
