### ISSUE TITLE
Bump to a new major version

### ISSUE THREAD

**Issue by ecaron** [dylants/price-finder#7]
Looking for confirmation that others think we should bump to v2.0.0 (given that the current master, once https://github.com/dylants/price-finder/pull/6 got pulled in, introduced breaking functionality.)

**Comment by dylants** [comment]
I agree, now that your feature has been merged in, we should bump the major version number and release. I'm unable to do it right now (sorry) but welcome you to if you'd like :)

By the way, the readme changes look great, thanks!

**Comment by ecaron** [comment]
Major version is ready. Either @dylants can do it, or do a `npm owner add ecaron price-finder` to give me the power to push it myself.

**Comment by ecaron** [comment]
Bump occurred at 427f0c89c889db8d7dffae0e1682ba73989ca70e, and 2.0.0 was tagged at that time too. Also added a CHANGELOG to reflect why the major version change was necessary.

**Comment by dylants** [comment]
Done!  I published the release and added you as an owner in npm.
