### ISSUE TITLE
Add support for staples.com!

### ISSUE THREAD

**Issue by rajkumarpb** [dylants/price-finder#80]
Need to add this too! It looks pretty famous from Alexa ratings. 

@dylants If you feel any of these site not worth doing, please just close the issue!

**Comment by dylants** [comment]
> If you feel any of these site not worth doing, please just close the issue!

In my opinion, the more sites and support the price-finder module has, the better for the community.  That being said, the sites that the community have added so far have been those that the community wanted to use.  So I guess I would pose the question to you: do _you_ think these sites (this one, #78, and #79) are worth adding? :smile:

**Comment by rajkumarpb** [comment]
The reason I raised the question was, 
1. I am not in US!
2. I am not a US Citizen.

So all the knowledge I have about US is via our dumb news and TV programmes. From what I can see and hear, it looks people flogged to walmart, target shops, but I never heard about their online portals. For me, if someone says online retail about US, it is Amazon, Newegg kinda sites. Since you are from US, I thought you have better understanding whether these are most used and whether we can go ahead and do it.

Anyways, I have done some digging and walmart seems to be top used among these three. So I will start working on it.

**Comment by dylants** [comment]
I think the fact that you are in a different part of the world is a benefit though!  This gives us a different viewpoint on the sites that would be useful to add to the module.  That's what I mean when I ask if it's important to you.  It's certainly hard to guess on if a site in a different part of the world is useful, that's probably why I haven't added any India sites! :smile:

**Comment by rajkumarpb** [comment]
I understand. I feel adding those sites make it much more complete. But I wanted to hear it from an American!

**Comment by dylants** [comment]
I'm going through old issues, and would like to close this issue out.  I'd like to retain the subset of sites within price finder that people want to use.  I'm not sure if there's a need from someone to have support for staples.com, so because of that, am going to close this issue.  If there is a desire to have support, we can add it of course.

Please let me know if this is an incorrect assumption.  Thanks!
